import { IMAGES_PATH } from "./paths";

export const DUMMY_CONTENTS = {
  contents: {
    6: "Pilihan Tepat untuk Wifi Hemat Tanpa Drama",
    7: "100%",
    8: "Fiber Optic",
    9: "1:1",
    10: "Simetris Download:Upload",
    11: "100%",
    12: "Internet UNLIMITED",
    13: `${IMAGES_PATH}/internet.png`,
    14: `Internetan Unlimited & Hemat? Pilihan Tepat: Mamura`,
    15: `Super lancar, super hemat, tanpa drama. #WifiMurah terbaik untuk segala kebutuhan Anda.`,
    16: `Cara Berlangganan Nikmati Wifi Internet Rumah di Mamura`,
    17: "Tiga langkah mudah untuk menggunakan layanan dari kami",
    18: "1. Registrasi",
    19: "Cek area lokasi pemasangan, pilih paket, dan pilih jadwal pemasangan.",
    20: "2. Instalasi",
    21: "Lacak proses instalasi kemudian nikmati layanan MamuraNet!",
    22: "3. Bayar",
    23: "Bayar tagihan dan nikmati kecepatan layanan  MamuraNet.",
    24: `${IMAGES_PATH}/about.png`,
    25: "Komitmen Kami untuk Koneksi Tanpa Batas!!",
    26: "PT Mamura Inter Media adalah penyedia layanan internet lokal yang telah melayani ribuan pelanggan sejak tahun [Tahun Berdiri]. Kami percaya bahwa internet cepat tidak harus mahal. Visi kami adalah menjadi pilihan utama WiFi hemat di Indonesia dengan:",
    27: "Infrastruktur jaringan yang modern",
    28: "Tim teknisi profesional dan responsif",
    29: "Layanan personal yang ramah dan cepat",
    30: "Kami hadir untuk menjawab kebutuhan internet Anda, mulai dari keluarga kecil hingga perusahaan besar.",
    31: "Siap Terkoneksi dengan Kami?",
    32: "Kami siap bantu Anda memilih layanan terbaik sesuai kebutuhan dan anggaran.",
    33: "🎯 Konsultasi gratis",
    34: "📍 Layanan area Jabodetabek & seluruh Indonesia",
    35: "📞 Fast response by phone & WhatsApp",
    36: "https://wa.me/62895622189054",
    37: `${IMAGES_PATH}/discuss_bnw.png`,
    38: "Frequently Ask Questions",
    39: "Layanan Internet Mamura",
    40: "https://wa.me/62895622189054",
    41: "Artikel Terbaru",
    42: "Mamura Inter Media berdiri sejak tahun 2020 telah melalui proses yang panjang dalam perjalanannya dengan fokus pada tujuan meningkatkan kualitas layanan jasa internet di Indonesia, sejalan dengan kemajuan teknologi yang terus berkembang pesat di era modern saat ini, dimana “Internet”telah menjadi bagian dari kebutuhan masyarakat umum.",
    43: "Jl. Raya Purwantoro - Pakis Baru KM. 08 Miri, Rt01 Rw01 Miri, Kismantoro, Wonogiri Kode Pos 57696",
    44: "Email info@mamura.net.id",
    45: "Whatsapp 0811-2539-694",
    46: "https://facebook.com",
    47: "https://instagram.com",
    48: "https://twitter.com",
    49: "https://linkedin.com",
    50: "Mamura Inter Media",
    51: "Artikel & Blog",
    52: "",
    53: "",
  },
  promo: [
    {
      image: {
        id: 1,
        file_url: `${IMAGES_PATH}/promo.png`,
      },
    },
    {
      image: {
        id: 2,
        file_url: `${IMAGES_PATH}/promo.png`,
      },
    },
  ],
  pricing: {
    home: [
      {
        id: 1,
        name: "Home Fiber Access 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        speed: 25,
        price: 185000,
        is_recommended: true,
      },
      {
        id: 2,
        name: "Home Fiber Access 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        speed: 45,
        price: 185000,
        is_recommended: false,
      },
      {
        id: 3,
        name: "Home Fiber Access 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        speed: 65,
        price: 185000,
        is_recommended: false,
      },
      {
        id: 4,
        name: "Home Fiber Access 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        speed: 100,
        price: 185000,
        is_recommended: false,
      },
    ],
    bussiness: [
      {
        id: 5,
        name: "Bisnis Fiber Access 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        speed: 100,
        price: 185000,
        is_recommended: true,
      },
      {
        id: 6,
        name: "Bisnis Fiber Access 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        speed: 200,
        price: 185000,
        is_recommended: false,
      },
      {
        id: 7,
        name: "Bisnis Fiber Access 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        speed: 300,
        price: 185000,
        is_recommended: false,
      },
      {
        id: 8,
        name: "Bisnis Fiber Access 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        speed: 400,
        price: 185000,
        is_recommended: false,
      },
    ],
  },
  faqs: [
    {
      id: 1,
      question: "Apa itu layanan internet dari Mamura?",
      answer:
        "Mamura adalah penyedia layanan internet berbasis fiber optik dengan koneksi cepat, stabil, dan harga terjangkau.",
    },
    {
      id: 2,
      question: "Apakah ada batasan kuota untuk internet Mamura?",
      answer:
        "Tidak. Semua paket internet Mamura bersifat UNLIMITED tanpa batasan kuota harian atau bulanan.",
    },
    {
      id: 3,
      question: "Berapa kecepatan internet yang ditawarkan?",
      answer:
        "Mamura menawarkan berbagai pilihan kecepatan mulai dari 20 Mbps hingga 100 Mbps, tergantung paket yang Anda pilih.",
    },
    {
      id: 4,
      question: "Apakah bisa pasang internet di area saya?",
      answer:
        "Silakan gunakan fitur 'Cek Jangkauan' di website kami atau hubungi tim kami melalui WhatsApp untuk informasi ketersediaan.",
    },
    {
      id: 5,
      question: "Berapa biaya pemasangan awal?",
      answer:
        "Biaya pemasangan awal mulai dari Rp150.000, tergantung lokasi dan jenis instalasi. Promo gratis pasang tersedia di area tertentu.",
    },
    {
      id: 6,
      question: "Bagaimana jika koneksi saya bermasalah?",
      answer:
        "Tim support Mamura siap membantu 24/7. Anda bisa menghubungi kami melalui WhatsApp atau call center untuk penanganan cepat.",
    },
  ],
  blogs: [
    {
      id: 1,
      thumbnail: {
        id: 101,
        file_name: "internet-tips.jpg",
        file_path: "/uploads/internet-tips.jpg",
        file_url: "https://picsum.photos/id/1015/600/400",
        file_mime_type: "image/jpeg",
        file_size: 125678,
        created_at: "2025-08-01T10:00:00Z",
        updated_at: "2025-08-01T10:00:00Z",
      },
      views: 1200,
      title: "Tips Memilih Internet Rumah yang Tepat",
      description:
        "Cari tahu bagaimana memilih paket internet sesuai kebutuhan rumah tangga dan jumlah pengguna.",
      blog_category: {
        id: 1,
        name: "Panduan",
        description: "Panduan memilih dan mengoptimalkan layanan internet",
        created_at: "2025-07-20T09:00:00Z",
        updated_at: "2025-07-20T09:00:00Z",
      },
      created_at: "2025-08-01T10:00:00Z",
      updated_at: "2025-08-01T10:00:00Z",
    },
    {
      id: 2,
      thumbnail: {
        id: 102,
        file_name: "fiber-optic.jpg",
        file_path: "/uploads/fiber-optic.jpg",
        file_url: "https://picsum.photos/id/1011/600/400",
        file_mime_type: "image/jpeg",
        file_size: 143256,
        created_at: "2025-08-02T11:30:00Z",
        updated_at: "2025-08-02T11:30:00Z",
      },
      views: 1200,
      title: "Kenapa Fiber Optic Lebih Unggul?",
      description:
        "Pelajari keunggulan fiber optic dibandingkan kabel tembaga dalam hal kecepatan dan stabilitas.",
      blog_category: {
        id: 2,
        name: "Teknologi",
        description: "Info tentang perkembangan dan manfaat teknologi internet",
        created_at: "2025-07-22T14:00:00Z",
        updated_at: "2025-07-22T14:00:00Z",
      },
      created_at: "2025-08-02T11:30:00Z",
      updated_at: "2025-08-02T11:30:00Z",
    },
    {
      id: 3,
      thumbnail: {
        id: 103,
        file_name: "wifi-coverage.jpg",
        file_path: "/uploads/wifi-coverage.jpg",
        file_url: "https://picsum.photos/id/1016/600/400",
        file_mime_type: "image/jpeg",
        file_size: 112300,
        created_at: "2025-08-03T08:45:00Z",
        updated_at: "2025-08-03T08:45:00Z",
      },
      views: 1200,
      title: "Cara Memperluas Jangkauan WiFi di Rumah",
      description:
        "Tips praktis untuk memperkuat sinyal WiFi agar koneksi tetap stabil di seluruh sudut rumah.",
      blog_category: {
        id: 1,
        name: "Panduan",
        description: "Panduan memilih dan mengoptimalkan layanan internet",
        created_at: "2025-07-20T09:00:00Z",
        updated_at: "2025-07-20T09:00:00Z",
      },
      created_at: "2025-08-03T08:45:00Z",
      updated_at: "2025-08-03T08:45:00Z",
    },
    {
      id: 4,
      thumbnail: {
        id: 102,
        file_name: "fiber-optic.jpg",
        file_path: "/uploads/fiber-optic.jpg",
        file_url: "https://picsum.photos/id/1011/600/400",
        file_mime_type: "image/jpeg",
        file_size: 143256,
        created_at: "2025-08-02T11:30:00Z",
        updated_at: "2025-08-02T11:30:00Z",
      },
      views: 1200,
      title: "Kenapa Fiber Optic Lebih Unggul?",
      description:
        "Pelajari keunggulan fiber optic dibandingkan kabel tembaga dalam hal kecepatan dan stabilitas.",
      blog_category: {
        id: 2,
        name: "Teknologi",
        description: "Info tentang perkembangan dan manfaat teknologi internet",
        created_at: "2025-07-22T14:00:00Z",
        updated_at: "2025-07-22T14:00:00Z",
      },
      created_at: "2025-08-02T11:30:00Z",
      updated_at: "2025-08-02T11:30:00Z",
    },
    {
      id: 5,
      thumbnail: {
        id: 101,
        file_name: "internet-tips.jpg",
        file_path: "/uploads/internet-tips.jpg",
        file_url: "https://picsum.photos/id/1015/600/400",
        file_mime_type: "image/jpeg",
        file_size: 125678,
        created_at: "2025-08-01T10:00:00Z",
        updated_at: "2025-08-01T10:00:00Z",
      },
      views: 1200,
      title: "Tips Memilih Internet Rumah yang Tepat",
      description:
        "Cari tahu bagaimana memilih paket internet sesuai kebutuhan rumah tangga dan jumlah pengguna.",
      blog_category: {
        id: 1,
        name: "Panduan",
        description: "Panduan memilih dan mengoptimalkan layanan internet",
        created_at: "2025-07-20T09:00:00Z",
        updated_at: "2025-07-20T09:00:00Z",
      },
      created_at: "2025-08-01T10:00:00Z",
      updated_at: "2025-08-01T10:00:00Z",
    },
  ],
  career: [],
};
